### ISSUE TITLE
replace bits_per_byte

### ISSUE THREAD

**Issue by Phantal** [a101010/bits#4]
https://github.com/a101010/bits/blob/4b7a18c661812c503057af5a4725d1aac67c6915/src/bits.hpp#L34

You can replace all uses of `BITS_IN_BYTE` with [`CHAR_BIT` from `climits`](https://en.cppreference.com/w/cpp/header/climits).  There's a similar macro in `values.h` (no C++ equivalent `cvalues`) called `BITSPERBYTE` but I'm having trouble finding anything that points to it being portable.

The [en.cppreference.com](https://en.cppreference.com/w/cpp/header/climits) reference above says `CHAR_BIT` == number of bits in a byte and `MB_LEN_MAX` is the max number of bytes in a multi-byte character.  I don't have a copy of the standard to look over to see whether that site is correct.  I would've expected it to mean number of bits in a char.

**Comment by Phantal** [comment]
According to [en.cppreference.com](https://en.cppreference.com/w/cpp/header/climits):

> `CHAR_BIT   == number of bits in a byte`
> `MB_LEN_MAX == maximum number of bytes in a multibyte character`

... so you could just do:

```
#include <climits>

// replace use of BITS_IN_BYTE with CHAR_BIT
```

**Comment by a101010** [comment]
Yeah, okay, but CHAR_BIT just isn't as meaningful. But I've now defined BITS_IN_BYTE in terms of CHAR_BIT. Fixed in https://github.com/a101010/bits/commit/b1c55b243a2104fb362236ef1100dfec2c7340ba.
