### ISSUE TITLE
Move to all unsigned under the hood

### ISSUE THREAD

**Issue by Phantal** [a101010/bits#5]
https://github.com/a101010/bits/blob/4b7a18c661812c503057af5a4725d1aac67c6915/src/bits.hpp#L116

If you use all unsigned under the hood there's two benefits:

* Only one implementation for both signed & unsigned
* No need to exclude any compilers

eg something like:

```
static_assert( std::is_unsigned<typeof(data)>::value, "Underlying data must be unsigned" );
const constexpr UnshiftedMask = (1 << MySizeInBits) - 1;
const constexpr Mask = UnshiftedMask << (HighBitPosition - MySizeInBits);
const constexpr MinT = std::is_unsigned<T>::value ? 0 : (1 + ~UnshiftedMask);

using unsigned_T = typename std::make_unsigned<T>::type;
unsigned_T getUnsignedValue() const { /*...*/ }
T getValue() const { return std::static_cast<T>( getUnsignedValue() ) - MinT; }
template <typename U>
void setValue( const U& u ) { data = data & ~Mask | Mask & (static_cast<unsigned_T>(u - MinT) << LeftShift); }
```

**Comment by a101010** [comment]
I think this is effectively closed in https://github.com/a101010/bits/commit/b1c55b243a2104fb362236ef1100dfec2c7340ba. We don't gain the benefit of the same implementation for signed and unsigned, but I don't think there are any issues with undefined behavior left. Let me know if I've missed something.
